### PR TITLE
Rewrite sorting algorithm

### PR DESCRIPTION
**Pull request by sukima**
When working with 'char' based movements that assumption prior was that the entire list was delimited by ', '. Issue #8 asked for handling alternative delimiters. I think this algorithm can accomplish that.

It will also allow the use of the around motion as it preserves prefix and suffix characters. The only assumption is that the selection is delimited consistently If the first delimiter is ', ' then all of them much match the same or things go wonky. (Future improvement maybe)

This also moves the cursor back to the beginning like most Vim motion commands do.

### CODE REVIEW

**Comment by christoomey** [comment]
Hi @sukima, thanks for sharing this. Unfortunately initial test for me showed that this breaks the existing functionality of sorting within an argument list:

```
var myFunction(context, e|vent, callback) {
}
```

In the above text with the cursor where the `|` is, `gsi)` would sort the arglist so it read `(callback, context, event)`. This currently works on `master`, but yields the following when run with your branch: `(, callba, event, ntext, )`.

Mind taking another look?

**Comment by sukima** [comment]
Confirmed. Will look into it.

**Comment by sukima** [comment]
@christoomey Can you try testing it now. I think I got it this time.

**Comment by christoomey** [comment]
LGTM. Thanks for the update!

**Pull request merged**
